/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMatrimonyRouteImport } from './routes/admin.matrimony'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBrowseRouteImport } from './routes/app.browse'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMyProfileRouteImport } from './routes/app.my-profile'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppShortlistRouteImport } from './routes/app.shortlist'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AdminMatrimonyIndexRouteImport } from './routes/admin.matrimony.index'
import { Route as AdminMatrimonyAuditLogsRouteImport } from './routes/admin.matrimony.audit-logs'
import { Route as AdminMatrimonyBannersRouteImport } from './routes/admin.matrimony.banners'
import { Route as AdminMatrimonyContentRouteImport } from './routes/admin.matrimony.content'
import { Route as AdminMatrimonyCouponsRouteImport } from './routes/admin.matrimony.coupons'
import { Route as AdminMatrimonyLoginRouteImport } from './routes/admin.matrimony.login'
import { Route as AdminMatrimonyMatchesRouteImport } from './routes/admin.matrimony.matches'
import { Route as AdminMatrimonyNotificationsRouteImport } from './routes/admin.matrimony.notifications'
import { Route as AdminMatrimonyPackagesRouteImport } from './routes/admin.matrimony.packages'
import { Route as AdminMatrimonyPaymentsRouteImport } from './routes/admin.matrimony.payments'
import { Route as AdminMatrimonyReportsRouteImport } from './routes/admin.matrimony.reports'
import { Route as AdminMatrimonySettingsRouteImport } from './routes/admin.matrimony.settings'
import { Route as AdminMatrimonyStoriesRouteImport } from './routes/admin.matrimony.stories'
import { Route as AdminMatrimonySubscriptionsRouteImport } from './routes/admin.matrimony.subscriptions'
import { Route as AdminMatrimonyTicketsRouteImport } from './routes/admin.matrimony.tickets'
import { Route as AdminMatrimonyUsersRouteImport } from './routes/admin.matrimony.users'
import { Route as AdminMatrimonyVerificationRouteImport } from './routes/admin.matrimony.verification'
import { Route as AppInterestsReceivedRouteImport } from './routes/app.interests.received'
import { Route as AppInterestsSentRouteImport } from './routes/app.interests.sent'
import { Route as AppMessagesIndexRouteImport } from './routes/app.messages.index'
import { Route as AppMessagesConversationIdRouteImport } from './routes/app.messages.$conversationId'
import { Route as AppMyProfileIndexRouteImport } from './routes/app.my-profile.index'
import { Route as AppMyProfileEditRouteImport } from './routes/app.my-profile.edit'
import { Route as AppProfilesProfileIdRouteImport } from './routes/app.profiles.$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatrimonyRoute = AdminMatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMyProfileRoute = AppMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShortlistRoute = AppShortlistRouteImport.update({
  id: '/shortlist',
  path: '/shortlist',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AdminMatrimonyIndexRoute = AdminMatrimonyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyAuditLogsRoute = AdminMatrimonyAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyBannersRoute = AdminMatrimonyBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyContentRoute = AdminMatrimonyContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyCouponsRoute = AdminMatrimonyCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyLoginRoute = AdminMatrimonyLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyMatchesRoute = AdminMatrimonyMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyNotificationsRoute =
  AdminMatrimonyNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminMatrimonyRoute,
  } as any)
const AdminMatrimonyPackagesRoute = AdminMatrimonyPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyPaymentsRoute = AdminMatrimonyPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyReportsRoute = AdminMatrimonyReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonySettingsRoute = AdminMatrimonySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyStoriesRoute = AdminMatrimonyStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonySubscriptionsRoute =
  AdminMatrimonySubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AdminMatrimonyRoute,
  } as any)
const AdminMatrimonyTicketsRoute = AdminMatrimonyTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyUsersRoute = AdminMatrimonyUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminMatrimonyRoute,
} as any)
const AdminMatrimonyVerificationRoute =
  AdminMatrimonyVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AdminMatrimonyRoute,
  } as any)
const AppInterestsReceivedRoute = AppInterestsReceivedRouteImport.update({
  id: '/interests/received',
  path: '/interests/received',
  getParentRoute: () => AppRoute,
} as any)
const AppInterestsSentRoute = AppInterestsSentRouteImport.update({
  id: '/interests/sent',
  path: '/interests/sent',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppMessagesConversationIdRoute =
  AppMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AppMessagesRoute,
  } as any)
const AppMyProfileIndexRoute = AppMyProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMyProfileRoute,
} as any)
const AppMyProfileEditRoute = AppMyProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppMyProfileRoute,
} as any)
const AppProfilesProfileIdRoute = AppProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/matrimony': typeof AdminMatrimonyRouteWithChildren
  '/app/browse': typeof AppBrowseRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/my-profile': typeof AppMyProfileRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortlist': typeof AppShortlistRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app/': typeof AppIndexRoute
  '/admin/matrimony/audit-logs': typeof AdminMatrimonyAuditLogsRoute
  '/admin/matrimony/banners': typeof AdminMatrimonyBannersRoute
  '/admin/matrimony/content': typeof AdminMatrimonyContentRoute
  '/admin/matrimony/coupons': typeof AdminMatrimonyCouponsRoute
  '/admin/matrimony/login': typeof AdminMatrimonyLoginRoute
  '/admin/matrimony/matches': typeof AdminMatrimonyMatchesRoute
  '/admin/matrimony/notifications': typeof AdminMatrimonyNotificationsRoute
  '/admin/matrimony/packages': typeof AdminMatrimonyPackagesRoute
  '/admin/matrimony/payments': typeof AdminMatrimonyPaymentsRoute
  '/admin/matrimony/reports': typeof AdminMatrimonyReportsRoute
  '/admin/matrimony/settings': typeof AdminMatrimonySettingsRoute
  '/admin/matrimony/stories': typeof AdminMatrimonyStoriesRoute
  '/admin/matrimony/subscriptions': typeof AdminMatrimonySubscriptionsRoute
  '/admin/matrimony/tickets': typeof AdminMatrimonyTicketsRoute
  '/admin/matrimony/users': typeof AdminMatrimonyUsersRoute
  '/admin/matrimony/verification': typeof AdminMatrimonyVerificationRoute
  '/app/interests/received': typeof AppInterestsReceivedRoute
  '/app/interests/sent': typeof AppInterestsSentRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/my-profile/edit': typeof AppMyProfileEditRoute
  '/app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/admin/matrimony/': typeof AdminMatrimonyIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/my-profile/': typeof AppMyProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/app/browse': typeof AppBrowseRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortlist': typeof AppShortlistRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app': typeof AppIndexRoute
  '/admin/matrimony/audit-logs': typeof AdminMatrimonyAuditLogsRoute
  '/admin/matrimony/banners': typeof AdminMatrimonyBannersRoute
  '/admin/matrimony/content': typeof AdminMatrimonyContentRoute
  '/admin/matrimony/coupons': typeof AdminMatrimonyCouponsRoute
  '/admin/matrimony/login': typeof AdminMatrimonyLoginRoute
  '/admin/matrimony/matches': typeof AdminMatrimonyMatchesRoute
  '/admin/matrimony/notifications': typeof AdminMatrimonyNotificationsRoute
  '/admin/matrimony/packages': typeof AdminMatrimonyPackagesRoute
  '/admin/matrimony/payments': typeof AdminMatrimonyPaymentsRoute
  '/admin/matrimony/reports': typeof AdminMatrimonyReportsRoute
  '/admin/matrimony/settings': typeof AdminMatrimonySettingsRoute
  '/admin/matrimony/stories': typeof AdminMatrimonyStoriesRoute
  '/admin/matrimony/subscriptions': typeof AdminMatrimonySubscriptionsRoute
  '/admin/matrimony/tickets': typeof AdminMatrimonyTicketsRoute
  '/admin/matrimony/users': typeof AdminMatrimonyUsersRoute
  '/admin/matrimony/verification': typeof AdminMatrimonyVerificationRoute
  '/app/interests/received': typeof AppInterestsReceivedRoute
  '/app/interests/sent': typeof AppInterestsSentRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/my-profile/edit': typeof AppMyProfileEditRoute
  '/app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/admin/matrimony': typeof AdminMatrimonyIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/my-profile': typeof AppMyProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/matrimony': typeof AdminMatrimonyRouteWithChildren
  '/app/browse': typeof AppBrowseRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/my-profile': typeof AppMyProfileRouteWithChildren
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shortlist': typeof AppShortlistRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/app/': typeof AppIndexRoute
  '/admin/matrimony/audit-logs': typeof AdminMatrimonyAuditLogsRoute
  '/admin/matrimony/banners': typeof AdminMatrimonyBannersRoute
  '/admin/matrimony/content': typeof AdminMatrimonyContentRoute
  '/admin/matrimony/coupons': typeof AdminMatrimonyCouponsRoute
  '/admin/matrimony/login': typeof AdminMatrimonyLoginRoute
  '/admin/matrimony/matches': typeof AdminMatrimonyMatchesRoute
  '/admin/matrimony/notifications': typeof AdminMatrimonyNotificationsRoute
  '/admin/matrimony/packages': typeof AdminMatrimonyPackagesRoute
  '/admin/matrimony/payments': typeof AdminMatrimonyPaymentsRoute
  '/admin/matrimony/reports': typeof AdminMatrimonyReportsRoute
  '/admin/matrimony/settings': typeof AdminMatrimonySettingsRoute
  '/admin/matrimony/stories': typeof AdminMatrimonyStoriesRoute
  '/admin/matrimony/subscriptions': typeof AdminMatrimonySubscriptionsRoute
  '/admin/matrimony/tickets': typeof AdminMatrimonyTicketsRoute
  '/admin/matrimony/users': typeof AdminMatrimonyUsersRoute
  '/admin/matrimony/verification': typeof AdminMatrimonyVerificationRoute
  '/app/interests/received': typeof AppInterestsReceivedRoute
  '/app/interests/sent': typeof AppInterestsSentRoute
  '/app/messages/$conversationId': typeof AppMessagesConversationIdRoute
  '/app/my-profile/edit': typeof AppMyProfileEditRoute
  '/app/profiles/$profileId': typeof AppProfilesProfileIdRoute
  '/admin/matrimony/': typeof AdminMatrimonyIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/my-profile/': typeof AppMyProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/community'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/login'
    | '/admin/matrimony'
    | '/app/browse'
    | '/app/messages'
    | '/app/my-profile'
    | '/app/search'
    | '/app/settings'
    | '/app/shortlist'
    | '/app/subscription'
    | '/app/upgrade'
    | '/app/'
    | '/admin/matrimony/audit-logs'
    | '/admin/matrimony/banners'
    | '/admin/matrimony/content'
    | '/admin/matrimony/coupons'
    | '/admin/matrimony/login'
    | '/admin/matrimony/matches'
    | '/admin/matrimony/notifications'
    | '/admin/matrimony/packages'
    | '/admin/matrimony/payments'
    | '/admin/matrimony/reports'
    | '/admin/matrimony/settings'
    | '/admin/matrimony/stories'
    | '/admin/matrimony/subscriptions'
    | '/admin/matrimony/tickets'
    | '/admin/matrimony/users'
    | '/admin/matrimony/verification'
    | '/app/interests/received'
    | '/app/interests/sent'
    | '/app/messages/$conversationId'
    | '/app/my-profile/edit'
    | '/app/profiles/$profileId'
    | '/admin/matrimony/'
    | '/app/messages/'
    | '/app/my-profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/community'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/login'
    | '/app/browse'
    | '/app/search'
    | '/app/settings'
    | '/app/shortlist'
    | '/app/subscription'
    | '/app/upgrade'
    | '/app'
    | '/admin/matrimony/audit-logs'
    | '/admin/matrimony/banners'
    | '/admin/matrimony/content'
    | '/admin/matrimony/coupons'
    | '/admin/matrimony/login'
    | '/admin/matrimony/matches'
    | '/admin/matrimony/notifications'
    | '/admin/matrimony/packages'
    | '/admin/matrimony/payments'
    | '/admin/matrimony/reports'
    | '/admin/matrimony/settings'
    | '/admin/matrimony/stories'
    | '/admin/matrimony/subscriptions'
    | '/admin/matrimony/tickets'
    | '/admin/matrimony/users'
    | '/admin/matrimony/verification'
    | '/app/interests/received'
    | '/app/interests/sent'
    | '/app/messages/$conversationId'
    | '/app/my-profile/edit'
    | '/app/profiles/$profileId'
    | '/admin/matrimony'
    | '/app/messages'
    | '/app/my-profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/community'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/register'
    | '/terms'
    | '/admin/login'
    | '/admin/matrimony'
    | '/app/browse'
    | '/app/messages'
    | '/app/my-profile'
    | '/app/search'
    | '/app/settings'
    | '/app/shortlist'
    | '/app/subscription'
    | '/app/upgrade'
    | '/app/'
    | '/admin/matrimony/audit-logs'
    | '/admin/matrimony/banners'
    | '/admin/matrimony/content'
    | '/admin/matrimony/coupons'
    | '/admin/matrimony/login'
    | '/admin/matrimony/matches'
    | '/admin/matrimony/notifications'
    | '/admin/matrimony/packages'
    | '/admin/matrimony/payments'
    | '/admin/matrimony/reports'
    | '/admin/matrimony/settings'
    | '/admin/matrimony/stories'
    | '/admin/matrimony/subscriptions'
    | '/admin/matrimony/tickets'
    | '/admin/matrimony/users'
    | '/admin/matrimony/verification'
    | '/app/interests/received'
    | '/app/interests/sent'
    | '/app/messages/$conversationId'
    | '/app/my-profile/edit'
    | '/app/profiles/$profileId'
    | '/admin/matrimony/'
    | '/app/messages/'
    | '/app/my-profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matrimony': {
      id: '/admin/matrimony'
      path: '/matrimony'
      fullPath: '/admin/matrimony'
      preLoaderRoute: typeof AdminMatrimonyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/browse': {
      id: '/app/browse'
      path: '/browse'
      fullPath: '/app/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-profile': {
      id: '/app/my-profile'
      path: '/my-profile'
      fullPath: '/app/my-profile'
      preLoaderRoute: typeof AppMyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shortlist': {
      id: '/app/shortlist'
      path: '/shortlist'
      fullPath: '/app/shortlist'
      preLoaderRoute: typeof AppShortlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/matrimony/': {
      id: '/admin/matrimony/'
      path: '/'
      fullPath: '/admin/matrimony/'
      preLoaderRoute: typeof AdminMatrimonyIndexRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/audit-logs': {
      id: '/admin/matrimony/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/matrimony/audit-logs'
      preLoaderRoute: typeof AdminMatrimonyAuditLogsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/banners': {
      id: '/admin/matrimony/banners'
      path: '/banners'
      fullPath: '/admin/matrimony/banners'
      preLoaderRoute: typeof AdminMatrimonyBannersRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/content': {
      id: '/admin/matrimony/content'
      path: '/content'
      fullPath: '/admin/matrimony/content'
      preLoaderRoute: typeof AdminMatrimonyContentRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/coupons': {
      id: '/admin/matrimony/coupons'
      path: '/coupons'
      fullPath: '/admin/matrimony/coupons'
      preLoaderRoute: typeof AdminMatrimonyCouponsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/login': {
      id: '/admin/matrimony/login'
      path: '/login'
      fullPath: '/admin/matrimony/login'
      preLoaderRoute: typeof AdminMatrimonyLoginRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/matches': {
      id: '/admin/matrimony/matches'
      path: '/matches'
      fullPath: '/admin/matrimony/matches'
      preLoaderRoute: typeof AdminMatrimonyMatchesRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/notifications': {
      id: '/admin/matrimony/notifications'
      path: '/notifications'
      fullPath: '/admin/matrimony/notifications'
      preLoaderRoute: typeof AdminMatrimonyNotificationsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/packages': {
      id: '/admin/matrimony/packages'
      path: '/packages'
      fullPath: '/admin/matrimony/packages'
      preLoaderRoute: typeof AdminMatrimonyPackagesRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/payments': {
      id: '/admin/matrimony/payments'
      path: '/payments'
      fullPath: '/admin/matrimony/payments'
      preLoaderRoute: typeof AdminMatrimonyPaymentsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/reports': {
      id: '/admin/matrimony/reports'
      path: '/reports'
      fullPath: '/admin/matrimony/reports'
      preLoaderRoute: typeof AdminMatrimonyReportsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/settings': {
      id: '/admin/matrimony/settings'
      path: '/settings'
      fullPath: '/admin/matrimony/settings'
      preLoaderRoute: typeof AdminMatrimonySettingsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/stories': {
      id: '/admin/matrimony/stories'
      path: '/stories'
      fullPath: '/admin/matrimony/stories'
      preLoaderRoute: typeof AdminMatrimonyStoriesRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/subscriptions': {
      id: '/admin/matrimony/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/matrimony/subscriptions'
      preLoaderRoute: typeof AdminMatrimonySubscriptionsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/tickets': {
      id: '/admin/matrimony/tickets'
      path: '/tickets'
      fullPath: '/admin/matrimony/tickets'
      preLoaderRoute: typeof AdminMatrimonyTicketsRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/users': {
      id: '/admin/matrimony/users'
      path: '/users'
      fullPath: '/admin/matrimony/users'
      preLoaderRoute: typeof AdminMatrimonyUsersRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/admin/matrimony/verification': {
      id: '/admin/matrimony/verification'
      path: '/verification'
      fullPath: '/admin/matrimony/verification'
      preLoaderRoute: typeof AdminMatrimonyVerificationRouteImport
      parentRoute: typeof AdminMatrimonyRoute
    }
    '/app/interests/received': {
      id: '/app/interests/received'
      path: '/interests/received'
      fullPath: '/app/interests/received'
      preLoaderRoute: typeof AppInterestsReceivedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interests/sent': {
      id: '/app/interests/sent'
      path: '/interests/sent'
      fullPath: '/app/interests/sent'
      preLoaderRoute: typeof AppInterestsSentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/messages/$conversationId': {
      id: '/app/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/messages/$conversationId'
      preLoaderRoute: typeof AppMessagesConversationIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/my-profile/': {
      id: '/app/my-profile/'
      path: '/'
      fullPath: '/app/my-profile/'
      preLoaderRoute: typeof AppMyProfileIndexRouteImport
      parentRoute: typeof AppMyProfileRoute
    }
    '/app/my-profile/edit': {
      id: '/app/my-profile/edit'
      path: '/edit'
      fullPath: '/app/my-profile/edit'
      preLoaderRoute: typeof AppMyProfileEditRouteImport
      parentRoute: typeof AppMyProfileRoute
    }
    '/app/profiles/$profileId': {
      id: '/app/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/app/profiles/$profileId'
      preLoaderRoute: typeof AppProfilesProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminMatrimonyRouteChildren {
  AdminMatrimonyAuditLogsRoute: typeof AdminMatrimonyAuditLogsRoute
  AdminMatrimonyBannersRoute: typeof AdminMatrimonyBannersRoute
  AdminMatrimonyContentRoute: typeof AdminMatrimonyContentRoute
  AdminMatrimonyCouponsRoute: typeof AdminMatrimonyCouponsRoute
  AdminMatrimonyLoginRoute: typeof AdminMatrimonyLoginRoute
  AdminMatrimonyMatchesRoute: typeof AdminMatrimonyMatchesRoute
  AdminMatrimonyNotificationsRoute: typeof AdminMatrimonyNotificationsRoute
  AdminMatrimonyPackagesRoute: typeof AdminMatrimonyPackagesRoute
  AdminMatrimonyPaymentsRoute: typeof AdminMatrimonyPaymentsRoute
  AdminMatrimonyReportsRoute: typeof AdminMatrimonyReportsRoute
  AdminMatrimonySettingsRoute: typeof AdminMatrimonySettingsRoute
  AdminMatrimonyStoriesRoute: typeof AdminMatrimonyStoriesRoute
  AdminMatrimonySubscriptionsRoute: typeof AdminMatrimonySubscriptionsRoute
  AdminMatrimonyTicketsRoute: typeof AdminMatrimonyTicketsRoute
  AdminMatrimonyUsersRoute: typeof AdminMatrimonyUsersRoute
  AdminMatrimonyVerificationRoute: typeof AdminMatrimonyVerificationRoute
  AdminMatrimonyIndexRoute: typeof AdminMatrimonyIndexRoute
}

const AdminMatrimonyRouteChildren: AdminMatrimonyRouteChildren = {
  AdminMatrimonyAuditLogsRoute: AdminMatrimonyAuditLogsRoute,
  AdminMatrimonyBannersRoute: AdminMatrimonyBannersRoute,
  AdminMatrimonyContentRoute: AdminMatrimonyContentRoute,
  AdminMatrimonyCouponsRoute: AdminMatrimonyCouponsRoute,
  AdminMatrimonyLoginRoute: AdminMatrimonyLoginRoute,
  AdminMatrimonyMatchesRoute: AdminMatrimonyMatchesRoute,
  AdminMatrimonyNotificationsRoute: AdminMatrimonyNotificationsRoute,
  AdminMatrimonyPackagesRoute: AdminMatrimonyPackagesRoute,
  AdminMatrimonyPaymentsRoute: AdminMatrimonyPaymentsRoute,
  AdminMatrimonyReportsRoute: AdminMatrimonyReportsRoute,
  AdminMatrimonySettingsRoute: AdminMatrimonySettingsRoute,
  AdminMatrimonyStoriesRoute: AdminMatrimonyStoriesRoute,
  AdminMatrimonySubscriptionsRoute: AdminMatrimonySubscriptionsRoute,
  AdminMatrimonyTicketsRoute: AdminMatrimonyTicketsRoute,
  AdminMatrimonyUsersRoute: AdminMatrimonyUsersRoute,
  AdminMatrimonyVerificationRoute: AdminMatrimonyVerificationRoute,
  AdminMatrimonyIndexRoute: AdminMatrimonyIndexRoute,
}

const AdminMatrimonyRouteWithChildren = AdminMatrimonyRoute._addFileChildren(
  AdminMatrimonyRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMatrimonyRoute: typeof AdminMatrimonyRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMatrimonyRoute: AdminMatrimonyRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppMessagesRouteChildren {
  AppMessagesConversationIdRoute: typeof AppMessagesConversationIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesConversationIdRoute: AppMessagesConversationIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppMyProfileRouteChildren {
  AppMyProfileEditRoute: typeof AppMyProfileEditRoute
  AppMyProfileIndexRoute: typeof AppMyProfileIndexRoute
}

const AppMyProfileRouteChildren: AppMyProfileRouteChildren = {
  AppMyProfileEditRoute: AppMyProfileEditRoute,
  AppMyProfileIndexRoute: AppMyProfileIndexRoute,
}

const AppMyProfileRouteWithChildren = AppMyProfileRoute._addFileChildren(
  AppMyProfileRouteChildren,
)

interface AppRouteChildren {
  AppBrowseRoute: typeof AppBrowseRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppMyProfileRoute: typeof AppMyProfileRouteWithChildren
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShortlistRoute: typeof AppShortlistRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInterestsReceivedRoute: typeof AppInterestsReceivedRoute
  AppInterestsSentRoute: typeof AppInterestsSentRoute
  AppProfilesProfileIdRoute: typeof AppProfilesProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseRoute: AppBrowseRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppMyProfileRoute: AppMyProfileRouteWithChildren,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShortlistRoute: AppShortlistRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppInterestsReceivedRoute: AppInterestsReceivedRoute,
  AppInterestsSentRoute: AppInterestsSentRoute,
  AppProfilesProfileIdRoute: AppProfilesProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
